### ISSUE TITLE
native js namespace imports thoughts

### ISSUE THREAD

**Issue by carocad** [thheller/reagent-expo#2]
hey @thheller,
I was just checking around the work that you did on shadow-cljs for react-native :)

To be honest I have never used shadow-cljs but since you took the time to build support for it I thought that it would be good to give you some feedback on it since I also did some react-native hacks when working on my project.

Here: https://github.com/thheller/reagent-expo/blob/master/src/main/test/app.cljs#L3

Is it also possible for shadow-cljs to use "normal" require statements like `(:require [expo :as ex])` ? From my understanding (see below), this is what it is currently implemented in the clojurescript compiler. I actually have my app built in such a way that `expo` can understand such statements (see [this](https://github.com/hiposfer/hive/blob/master/src/hive/screens/home/core.cljs#L4)). I use a simple pre-process step to figure out the things that I had to import in advance (just a short description since I dont know how relevant it is 😅).

> From my understanding (see below), this is what it is currently implemented in the clojurescript 

Some of the latest npm changes is the use of `@` in the module string to symbolize organizations, for example: `@expo/vector-icons`. I tried this with my setup but couldnt get the cljs compiler to accept it :( (see figwheel [issue](https://github.com/bhauman/lein-figwheel/issues/717)).

It would be interesting to see if shadow-cljs can already deal with this case or if it would need a change directly to the cljs compiler

**Comment by thheller** [comment]
The reason I do not recommend using symbols is because they are "magic". That means that you can only use `[expo :as ex]` if and only if the `<project-root>/node_modules/expo` package is installed. I do not like this limitation and the extra guess involved if this is a normal CLJS namespace or an `npm` import.

`shadow-cljs` does support symbols. However it is strongly recommended to ALWAYS use strings for `npm` requires, exactly because the problems you mention around things like `@expo/vector-icons` which cannot be turned into symbols. Also there is no ambiguity in mapping `_`, `-` or `/`. `shadow-cljs` has no problem with these and works just fine. Strings are "accepted" in the standard CLJS compiler as well, just not widely used since support for direct `npm` includes is rather bad currently.

**Comment by carocad** [comment]
> `shadow-cljs` does support symbols

yeah, this was my main concern since most tutorials and blog post on the topic, that I have read, show the usage with symbols not with strings. Glad to hear that both are supported but only one is encouraged.

> Strings are "accepted" in the standard CLJS compiler as well, just not widely used since support for direct `npm` includes is rather bad currently.

I couldnt get this working though. At least not with my setup. Maybe because of the whole react-native, expo, figwheel-bridge .... too many moving pieces.

Thanks for the info and the fast answer :)
